### ISSUE TITLE
There're 2 memes in the screen

### ISSUE THREAD

**Issue by Dragon-0609** [ani-memes/AMII#108]
### I noticed that sometimes, there're 2 memes:

![bandicam 2021-05-14 21-44-53-812](https://user-images.githubusercontent.com/80271099/118302739-08f68a80-b4fe-11eb-9a50-03d3fc7bbb63.jpg)

![bandicam 2021-05-14 21-44-58-883](https://user-images.githubusercontent.com/80271099/118302761-0eec6b80-b4fe-11eb-9d24-d6c95da1ed8f.jpg)

![bandicam 2021-05-14 21-45-04-376](https://user-images.githubusercontent.com/80271099/118302782-14e24c80-b4fe-11eb-88e0-09093fa07c6a.jpg)

At first time, I didn't give attention. But after I started to notice it more and more. I thought you will remove it in new versions, but nothing was changed. 
I have to close _PHPStorm_, if I want to hide 2nd meme. I can hide 1st meme, but second not clickable, it doesn't repsonse to my clicks.

**My IDE:**

PhpStorm 2020.3.3
Build #PS-203.7717.64, built on March 16, 2021
Runtime version: 11.0.10+8-b1145.96 amd64
Windows 10 10.0

Note: I had this bug in old _PHPStorm_.

**Comment by Unthrottled** [comment]
Do you have a reliable way to reproduce this issue?

For instance, does it only happen with the `Log Alert` notifications and test notifications? Taking a guess based on the everlasting meme (and the fact that I don't really use the `Log Alert` which is why I might have not caught this)

**Comment by Dragon-0609** [comment]
Sorry, but I don't understand what you mean by `Log Alert`. If you mean tests, I don't use tests in _PHPStorm_. I just write code in php. Anime Memes is shown sometimes, when my IDE is in idle. I don't know how it shows 2 memes, but sometimes it's happens.

**Comment by Unthrottled** [comment]
Okay, so it just happens when you idle for some period of time.

I've never seen this issue come up since I've last fixed it. 
Which is why I haven't fixed it :) 

I'll try to replicate the issue, if I can't the best I could do is give you a `Force Clear` notifications, which _should_ clear any displayed gifs.

**Comment by Unthrottled** [comment]
Hey! So I wasn't able to replicate the issue. However, I threw some code in that _will_ clear any previous memes when a new one is about to come up. I also added [clear memes](https://github.com/ani-memes/AMII#clear-memes) for whatever reason my fix doesn't work.

Considering I just released the plugin, I'm going to wait to publish this. You can [manually install the latest version following these instructions](https://github.com/ani-memes/AMII#installation)

Thanks for your understanding and patience with this issue :)

**Comment by Dragon-0609** [comment]
Ok, no problem. Anyway, thanks.

**Comment by Dragon-0609** [comment]
Hi. This issue has replied again. At this time I recorded it to video. Also, I got this issue when set up Preferences. After passing several minutes (5-15), it is shown.  I tried to reproduce issue, but it is not shown (you will see in video). 
Video:
https://drive.google.com/file/d/15JKgnFyRE0gDH-R4wjSys6QEk8lROcDG/view?usp=sharing

**Comment by Unthrottled** [comment]
I think you are not running the version with that fixed, friend.

I saw your options window in the video, it was missing the `Clear Memes` option, which tells me that `v0.10.3` isn't installed, but an older version. Can you confirm?

![Peek 2021-05-31 13-28](https://user-images.githubusercontent.com/15972415/120230215-7bf94400-c214-11eb-9355-9eedc5fece70.gif)

You've got a nice desktop setup BTW :ok_hand:

**Comment by Dragon-0609** [comment]
Are there 0.10.3? My version 0.10.2.

**Comment by Dragon-0609** [comment]
Do I have to update PHPStorm to 2021.2? Now it's clear for me why there aren't update for plugin.

**Comment by Dragon-0609** [comment]
> You've got a nice desktop setup BTW 👌

Thanks

**Comment by Unthrottled** [comment]
> Do I have to update PHPStorm to 2021.2? Now it's clear for me why there aren't update for plugin.

@Dragon-0609 So are you good? If not [please see this comment](https://github.com/ani-memes/AMII/issues/108#issuecomment-843057970)

I'll probably be releasing `v0.10.4` in the near future (because of the 2021.2 EAP support).
