### ISSUE TITLE
Broken Link. Not able to install plugin in intellij ultimate

### ISSUE THREAD

**Issue by ahil-k** [ani-memes/AMII#119]
Plugin link is broken. https://plugins.jetbrains.com/files/15865/122711/Anime+Memes.0.10.6.zip?updateId=122711&pluginId=15865&family=INTELLIJ

**Comment by Unthrottled** [comment]
Thanks for reporting this issue!

I've submitted a [marketplace issue](https://youtrack.jetbrains.com/issue/MP-3580). You can track the progress there. 

You can also manually download the [latest release](https://github.com/ani-memes/AMII/releases/latest) and install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd> or use the IDE built-in plugin system <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>Marketplace</kbd> > <kbd>Search for "Anime Memes"</kbd> >
  <kbd>Install Plugin</kbd>, to get around the issue.
