### ISSUE TITLE
Request: resizing / fixed sizing

### ISSUE THREAD

**Issue by fluffynuts** [ani-memes/AMII#120]
Hi, I'm really enjoying this extension (makes passing / failing tests a little more fun!)

I'd just like to ask if it would be possible to provide configuration for the size of the image - I'd like it to take up a smaller area, so it doesn't obscure anything. Alternatively, being able to dock the output somewhere would also work

Thanks!

**Comment by Unthrottled** [comment]
> Alternatively, being able to dock the output somewhere would also work

Are you talking about something different than these settings?

![image](https://user-images.githubusercontent.com/15972415/127479287-daf6b241-e65d-4d61-810f-f01c870fed1b.png)
![image](https://user-images.githubusercontent.com/15972415/127479339-d9bb4fc0-138c-4251-be56-6d53a83ce7bb.png)

The filled in box of the `Position` grid denotes where the image will be placed when it shows up.

> would be possible to provide configuration for the size of the image 

I'll have some time later to look into that. Answer is probably, yeah.

**Comment by fluffynuts** [comment]
Yeah, I've already placed the image to the bottom right, but it's still quite large, so it obscures the output in the test runner a bit - though I do enjoy the feedback :D

**Comment by Unthrottled** [comment]
So I plan on adding an option to specify a `Maximum Width/Height` that will make the image as big as the largest specified dimension (as to preserve the ratio).

Think that covers the requirement.

**Comment by Unthrottled** [comment]
Hey fam, thanks for the suggestion. I've submitted the update for approval. Probably might take a couple of days to be approved. Will follow up when the release is available.
