### ISSUE TITLE
feature-request: Meme Content Visualization Preview

### ISSUE THREAD

**Issue by zaerald** [ani-memes/AMII#121]
## Motivation

Whenever users try to prefer or blacklist characters from the settings, it's hard to know which part of the assets are affected.

![Screenshot from 2021-08-01 02-19-16](https://user-images.githubusercontent.com/21978370/127749344-94ad0207-50fc-4726-85b4-faf299e05443.png)
*wip...please ignore the bad UI for now*

I'm trying to build this whenever user select the anime or character, it'll show up the asset on the right resizable pane if it's already available locally. If not, it'll show a simple button that, when clicked, it'll download the asset, so the user can see the preview.

@Unthrottled let me know your thoughts.

**Comment by Unthrottled** [comment]
I like the idea! I think it could also be expanded later on as well. Such as showing statistics (how often you have seen this), giving more weight to specific assets, excluding specific assets, and other stuff.

>  If not, it'll show a simple button that, when clicked, it'll download the asset, so the user can see the preview.

Please do make sure this is a thing. Would like to avoid users downloading a bunch of assets, then not being  a long time user. I don't mind paying for their bandwidth costs, as long as they continue to enjoy the plugin. My AWS bill keeps going up every month :sweat_smile: . However, I think (if done right) the amount of bandwidth increase from this feature, should be negligible.

**Comment by zaerald** [comment]
I'm thinking of whenever the character preview has multiple visualizations (i.e. more than 1). The download preview will only get one asset and not to download everything, so the user will just get a good idea of what that character looks like.

**Comment by Unthrottled** [comment]
Oh yeah, if you happen to run into any issues with the images not showing with the correct width & height, during development.  Then switch the project JDK to be the JetBrains Runtime. Ran into that issue today.

![image](https://user-images.githubusercontent.com/15972415/128646219-76d79a06-40d2-480c-bc51-a18f8fada469.png)
