### ISSUE TITLE
Cannot show gif pictures on idea 2021

### ISSUE THREAD

**Issue by oumindong** [ani-memes/AMII#135]
It just showed my local gif locations.

![image](https://user-images.githubusercontent.com/85326769/143584409-a0083a35-2faa-44dd-8a81-be3dcb8ff7ee.png)

![Ur4yi8JfPW](https://user-images.githubusercontent.com/85326769/143584436-663027f5-d419-4cd3-ae8c-486409f08349.png)

**Comment by Unthrottled** [comment]
Hmm, that is curious I have a couple of questions.

1. Can you give me information about your IDE? You can find it in `Help` -> `About`. 
Here is mine as an example
```
IntelliJ IDEA 2021.3 RC (Ultimate Edition)
Build #IU-213.5744.202, built on November 24, 2021
Licensed to Alex Simons
Subscription is active until February 20, 2022.
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-90-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry:
    ide.color.picker.new.pipette=true

Non-Bundled Plugins:
    one.util.ideaplugin.screenshoter (1.7.1)
    io.unthrottled.theme.randomizer (0.2.1)
    io.acari.normandy.progress.bar (1.9.11)
    com.markskelton.one-dark-theme (5.4.0)
    com.jetbrains.ChooseRuntime (1.2)
    com.fwdekker.randomness (2.7.3)
    io.acari.DDLCTheme (21.0.0)
    io.unthrottled.amii (0.13.0)
    String Manipulation (8.22.203.000.1)
    IdeaVIM (1.8.1)
    Pythonid (213.5744.202)
    MavenRunHelper (4.18.212.000.3)
    UsefulActions (2.4)

Kotlin: 213-1.5.10-release-949-IJ5744.202
Current Desktop: ubuntu:GNOME
```

2. Are there any gifs in `C:\Users\yourName\AppData\Roaming\Jetbrains\amiiAssets\visuals\` ?

**Comment by oumindong** [comment]
1、IntelliJ IDEA 2021.2.2 (Community Edition)
Build #IC-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1955M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: Statistic (4.1.7), com.jetbrains.CyanTheme (1.2), com.markskelton.one-dark-theme (5.4.0), com.hiberbee.intellij.hiberbee-theme (2021.9.23.2312), net.antelle.intellij-xcode-dark-theme (1.2.4), de.ax.powermode (100.001), com.jetbrains.darkPurpleTheme (1.2), GsonFormatPlus (1.6.1), org.sonarlint.idea (6.3.0.39716), jd-intellij (0.8.1), CheckStyle-IDEA (5.57.2), com.godwin.json.parser (1.4.2), ink.organics.pojo2json (1.1.0), net.vektah.codeglance (1.5.4), io.unthrottled.amii (0.13.0), com.alibaba.p3c.smartfox (2.1.1), OdpsStudio (3.7.1), com.codota.csp.intellij (4.2.10), com.thvardhan.gradianto (4.4), some.awesome (1.14), com.baomidou.plugin.idea.mybatisx (1.5.1), izhangzhihao.rainbow.brackets (6.21), cn.cloud.auto.restful.tool (1.4.4), me.jinghong.restful.toolkit (1.0.0), SequenceDiagram (2.1.3), com.bruce.intellijplugin.generatesetter (2.8), cn.yiiguxing.plugin.translate (3.2.0.1), zielu.gittoolbox (212.8.1)
Kotlin: 212-1.5.10-release-IJ5284.40

2、There are gifs in my directory 
![image](https://user-images.githubusercontent.com/85326769/143795369-542c984d-4247-4582-92d4-c3974df8ea6a.png)

**Comment by oumindong** [comment]
Also when I click the directory, it shows the information of the gif

![image](https://user-images.githubusercontent.com/85326769/143795511-f9b4b916-a30f-49d6-b6bb-c5ebc14732a5.png)

**Comment by Unthrottled** [comment]
Thank you for supplying this information. I'll look into a fix later this week. I suspect it has something to do with the 汉字 or the `'` in your path, thanks!

**Comment by oumindong** [comment]
Chinese can be excluded.

![image](https://user-images.githubusercontent.com/85326769/143968935-4ca50ecb-42d1-4c8b-9c3f-559c2dda2fb3.png)

**Comment by oumindong** [comment]
The new release works! Thanks very much~
