### ISSUE TITLE
Multiple overlays from different projects when specific files are open

### ISSUE THREAD

**Issue by armisael** [ani-memes/AMII#138]
First of all, let me thank you for this great extension! I've been using it for a while now, and since it seems it'll stay with me for another while, I decided it's worth raising this issue I have since the very beginning.

I fear it's hard to explain it, so let me take the long route: MacOS - starting from Big Sur - allows to group multiple windows of the same application into one, using tabs; this works with JetBrains products (even though apparently it was not intended on their side) -- see https://youtrack.jetbrains.com/issue/JBR-2893

This means I can open multiple projects in the same window:
![utvpIW9_UNvHiRAAnAkPCw](https://user-images.githubusercontent.com/71387/150117578-5615f967-a474-4594-b2cc-d7bba4d9c750.png)

Now, AMII works great in this setup: if I work on a project, then switch to another one that has been inactive for a while, I'm welcomed with a nice meme; I smile, I click, it disappears, everything is smooth... until I open a .md file... For some reason, when I do, all the memes of the other projects appear, stacking on top of each other:
![Schermata 2022-01-19 alle 12 15 47](https://user-images.githubusercontent.com/71387/150119527-3df79990-1245-41ed-aeec-97fb5a70f113.png)

I think this is related to the IDE opening the builtin browser to show some HTML, as it happens:
- when I open an .md file and want to see the preview;
- when I open a .html file and want to see the preview.

Given this grouping feature is native and specific to MacOS, and that its support was not directly enabled by JetBrains, I understand that debugging and fixing this issue might be tough, but I thought it's worth at least mentioning it here.

**Comment by Unthrottled** [comment]
> I think this is related to the IDE opening the builtin browser to show some HTM

Fairly confident that this is the issue. The Embedded Browser (JCEF), is a jerk and causes a bunch of trouble.

I don't know if you've noticed but it also affect any of the popup notifications, too.

Anything that intersects (across project windows) with any open JCEF window's bounding box automatically gets detached and floats to the top. 

Anyways, I run into this a bunch too when I am working on my Mac. I'll see what I can do, or if I need to complain to JetBrains.

Thanks for taking the time to report this issue!

**Comment by Unthrottled** [comment]
Hey, I don't know if you still care or not, but as of the build `221.4165`, this problem has been fixed in the platform 🎉 

So once 2022.1 comes out, I'll close this issue.

**Comment by armisael** [comment]
I definitely care! Thank you! I just updated PyCharm to 2022.1 EAP (PY-221.3427.103), I'll test it as soon as MIKU is compatible with > 213.

**Comment by Unthrottled** [comment]
Cool, I'm probably going to wait a bit before I release the plugin to the marketplace. You can follow the [manual installation instructions](https://github.com/ani-memes/AMII#installation) if you want the update sooner.

**Comment by Unthrottled** [comment]
`#PY-221.3427.103` < `221.4165` , So I think the next EAP build for Pycharm will work.

**Comment by armisael** [comment]
Ahah damn, apparently I can't read :-) thank you!

**Comment by Unthrottled** [comment]
I think the 2022.1 build is generally available now. 🎉
