### ISSUE TITLE
Feature-request: Copy the link on pressing the meme with right button of the mouse

### ISSUE THREAD

**Issue by Dragon-0609** [ani-memes/AMII#139]
I'm glad you added the feature that displays the source of a meme. 

#### In this request what I want?
Displaying the source of the meme is very cool, but there's some memes, that is unknown. Sometimes, I try to find info about source of unknown memes, but in `amii-assets.unthrottled.io` I can distinguish memes with unknown source from known source by clicking through all of them and checking if they have `Unknown female`. This is not very convenient.
Sometimes I see in the IDE a meme that I would like to watch its anime, but it has unknown source, so it's impossible. It would be cool if I can get direct link to its page in `amii-assets.unthrottled.io` by clicking right button of the mouse. By that it would be much easier to find infos of memes.

**Comment by Dragon-0609** [comment]
Or, if the meme has unknown source, put a text `Copy link` next to `Stop Showing Info`.

**Comment by Unthrottled** [comment]
@Dragon-0609 If you ever go to a link directly does this happen to you?

![image](https://user-images.githubusercontent.com/15972415/152448442-a23f5dab-be13-4403-a57f-ffe6ed9284d3.png)

Sample: https://amii-assets.unthrottled.io/assets/view/d9e6e0126e9cf8ca543a1ca26c9b176c

**Comment by Dragon-0609** [comment]
> If you ever go to a link directly does this happen to you?

It happened when I had opened by `Open in new tab`. But if I open in main page just by clicking on it, it is opened immediately.
Can't you add script to redirect from main page?
For example: 
`https://amii-assets.unthrottled.io/?redirect=<id of meme 'd9e6e0126e9cf8ca543a1ca26c9b176c' or 'assets/view/d9e6e0126e9cf8ca543a1ca26c9b176c'>
If you redirect from main page, I'm sure it will be opened properly.

**Comment by Unthrottled** [comment]
Ah, the issue is in some of the rendering code. It is a single page application (eg the same index.html is used for all routes), I just didn't do enough of a good job to handle loading the app on that route. Will let you know when is fixed.

**Comment by Unthrottled** [comment]
@Dragon-0609 Fairly confident that I fixed the white screen issue, let me know if it happens to you again. If it does, could you make sure that the browser hasn't cached an older version of the content?
