### ISSUE TITLE
MIKU speaks Korean

### ISSUE THREAD

**Issue by hedi-sellami-shift** [ani-memes/AMII#144]
Not a bug or a feature request, I just wanted to ask.

I was wondering if it's a weird config setting on my side or if it's by design?

I would have expected the plugin to speak in Japanese, or maybe in English so more people can understand it.

Is it possible to change the spoken language?

**Comment by Unthrottled** [comment]
> I was wondering if it's a weird config setting on my side or if it's by design?

It wasn't intentional. I have the ability to associate one sound asset to a visual asset. Guess I took the animation from a Korean dub. Do you remember which one it was? You can browse all of the assets here: https://amii-assets.unthrottled.io/

> Is it possible to change the spoken language?

No, it is not.

**Comment by hedi-sellami-shift** [comment]
Thanks for your prompt reply!
Until now, I only got silent memes. But I checked a few memes with sounds on the db, and they seem to be fine.

However that speaks to you sometimes (for the greeting on startup for example) seems to always be in korean. I don't think it's attached to any visual asset.
