### ISSUE TITLE
Allow options for fade

### ISSUE THREAD

**Issue by romangraef** [ani-memes/AMII#145]
Allow a fast dismissal option (maybe a setting for fade time) that disables the fade out of images. I have my images on top of my run button and if i just misspell one variable it sometimes takes longer to wait for the image to disappear, then the combined time of fixing my spelling mistake and clicking run again (especially if i forgot to first dismiss the image and then fix my error)

**Comment by Unthrottled** [comment]
Right now, things are set up such that the gif will at least get one full playthrough. So if it is a _long_ gif, I don't think the faster fade out time will work.

>  spelling mistake and clicking run again (especially if i forgot to first dismiss the image and then fix my error)

So you are are that you can click the displayed image, and click outside of it to dismiss it before it completes? That isn't sufficient? If not you could bind a shortcut to the [clear meme action](https://github.com/ani-memes/AMII#clear-memes).
