### ISSUE TITLE
Custom Assets

### ISSUE THREAD

**Issue by Unthrottled** [ani-memes/AMII#151]
Allow users to be able to supply, tag, and use their own custom assets they have on their local machine.

**Comment by Dragon-0609** [comment]
Will be there an option, which allows the combining of local and global assets?

For example, I won't spend much time adding many custom assets. Maximum 2-5 assets. So, it'd be great to be able to use local and global assets.

**Comment by Unthrottled** [comment]
> Will be there an option, which allows the combining of local and global assets?

The idea was that the custom assets would just automatically be added to the pool of assets already provided by the plugin. I don't think there is much of a use case to only use assets provided by the user.

**Comment by Dragon-0609** [comment]
> > Will be there an option, which allows the combining of local and global assets?
> 
> The idea was that the custom assets would just automatically be added to the pool of assets already provided by the plugin. I don't think there is much of a use case to only use assets provided by the user.

OK Then.

**Comment by Unthrottled** [comment]
Just adding some feature notes:

- Custom visual assets will work by configuring a directory where images/gifs can be placed/dropped into.
- Custom assets in the configured custom assets directory will be available to be tagged for usage.
- Image tagging consists of a category (gender assignment probably won't be supplied because the user is adding only things they like)
- Only custom assets that are tagged will be used by MIKU.
- Custom visual assets will manually have to be associated with an audio asset.
- Custom asset directory & tagging should be shared across IDEs local on the machine.
- Custom assets by default will be pooled with the assets provided by the plugin by default.
- @Dragon-0609 Changed my mind, I think with the feature as described might lend towards an option to only show custom assets.
- Only custom asset mode _will not_ download assets from the meme repository, and will not check for updates of new memes. 
- Allow custom assets to be tagged as `Cultured` (suggestive 😉 )
- Add toggle-able `Cultured` mode that needs to be enable to show `Cultured` custom assets.
- Meme-info on click for a custom asset should yield a no-op message.
- Custom asset settings should be reset-able by the configuration menu.
- Custom visual assets assets should be deleteable by the settings UI (should probably have a toggle-able delete mode for a better UX)
- Deletes are not able to be undone. 
- Custom memes should be testable from the settings menu.
