### ISSUE TITLE
Will the "Test results@ reaction work for Apex unit tests?

### ISSUE THREAD

**Issue by melu5ha** [ani-memes/AMII#152]

**Comment by melu5ha** [comment]
Yes, it is.

**Comment by Unthrottled** [comment]
@melu5ha Do you use a special plugin to run these tests, if so, can you share what it is. Is it this? https://plugins.jetbrains.com/plugin/7831-illuminated-cloud

**Comment by melu5ha** [comment]
Most people use this plugin https://plugins.jetbrains.com/plugin/10253-illuminated-cloud-2

**Comment by Unthrottled** [comment]
Got it, I'll have to write an integration to the plugin that supports the Apex Unit tests, just trying to make sure I choose the right one.

**Comment by melu5ha** [comment]
Thank!!!
