### ISSUE TITLE
Anime source name pop-up window

### ISSUE THREAD

**Issue by Mus3761** [ani-memes/AMII#155]
So, whenever we are shown a GIF and if we clicked on it, we would get the info about the character in the GIF and which anime it is from. I accidentally clicked on the "Don't show this info again" or button with a similar statement and now I can't re-enable it.

**Comment by Dragon-0609** [comment]
You can enable it in:
`Settings` -> `Other Settings` -> `AMII Settings`.
There's `Info On Click`. Check it.

NOTE: I wrote for Rider, but in other IDEs should be similar.

**Comment by Unthrottled** [comment]
What @Dragon-0609 said, looks like that still works as expected 

https://user-images.githubusercontent.com/15972415/187794867-4e7bc8cd-cf9f-465e-8611-3d4fc481d2b0.mp4

Please confirm.

**Comment by Mus3761** [comment]
> 

It worked. Thank you very much!

p.s. thanks for this zero two theme as well. loving it and using it rn too!!
