### ISSUE TITLE
Have always sound on test completion. 

### ISSUE THREAD

**Issue by Legion112** [ani-memes/AMII#156]
I would like to force always have sound notification on test failer. This would help me to return back to work after long time of procastination during waiting for test result.

**Comment by Dragon-0609** [comment]
Not all memes have sound.
So, I think @Unthrottled could add an option to show just memes with sound for build results like successful built, build failed and etc.

**Comment by Legion112** [comment]
That would be greate.

**Comment by Legion112** [comment]
Where I can see list of meme wich has sound? Maybe I could limit only those which has it?

**Comment by Dragon-0609** [comment]
Here you can see all memes:
https://amii-assets.unthrottled.io/

**Comment by Dragon-0609** [comment]
I think at the moment there's no filter for memes with and without sounds in that website. So, you can just press in every meme and see if it has the sound.

**Comment by Unthrottled** [comment]
Ah yeah, [the older version of the plugin](https://github.com/waifu-motivator/waifu-motivator-plugin/pull/289) used to randomly associate a sound to a visual asset (I think, don't remember). So I feel it's fair to resurrect it. 

Anyways, with custom assets, I think I can add the ability for users to provide a pool of sound assets. They can be tagged with: `Positive`, `Negative`, `Neutral` (or some other mapping) that allows me to associate a visual asset with an audible asset. 

Then I can add a setting for each event type (startup, test, exit code, etc) as to whether play a random sound, from the random audible asset pool, on event dispatch.

I might work on this sooner if I feel like procrastinating on what I am currently working on.

**Comment by Legion112** [comment]
Could you provide a list of command what need to be run in order to build project?
So contribution would be mush simpler. 
@Unthrottled

**Comment by Legion112** [comment]
@Unthrottled sure you could list it.
