### ISSUE TITLE
AMII shows incorrect reaction when debugging a flutter test

### ISSUE THREAD

**Issue by pohuing** [ani-memes/AMII#157]
The assistant gets angry even if the tests pass in ad-hoc debug runs:

https://user-images.githubusercontent.com/24683548/190932631-a0202ee6-9adf-485c-9f7c-8989f37e33b3.mp4

Non debug runs work fine however.

```
IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Build #IU-222.3739.54, built on August 16, 2022
Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 11448M
Cores: 24
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.watches.in.variables=false

Non-Bundled Plugins:
    some.awesome (1.14)
    com.wakatime.intellij.plugin (14.1.1)
    com.codertainment.scrcpy (1.0.0)
    io.acari.DDLCTheme (88.1-1.4.0)
    io.unthrottled.amii (0.15.1)
    Key Promoter X (2022.2)
    PlantUML integration (5.17.1)
    Dart (222.3739.24)
    com.localizely.flutter-intl (1.17.3-2020.3)
    MavenRunHelper (4.21.222.2964.0)
    io.flutter (70.0.5)
    de.mariushoefler.flutter_enhancement_suite (1.6.0)
    izhangzhihao.rainbow.brackets (6.26)

Kotlin: 222-1.7.10-release-334-IJ3739.54
```

**Comment by Unthrottled** [comment]
I am unable to replicate the issue with this environment

**Intellij**
``` 
IntelliJ IDEA 2022.2.2 (Ultimate Edition)
Build #IU-222.4167.29, built on September 13, 2022
Runtime version: 17.0.4+7-b469.53 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Non-Bundled Plugins:
    io.acari.DDLCTheme (84.2-1.3.0)
    io.unthrottled.amii (1.0.1)
    Dart (222.3739.24)
    io.flutter (70.0.5)
```
**Flutter**

```
λ → flutter --version                                                                                  
Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e3c29ec00c (5 days ago) • 2022-09-14 08:46:55 -0500
Engine • revision a4ff2c53d8
Tools • Dart 2.18.1 • DevTools 2.15.0
```


https://user-images.githubusercontent.com/15972415/191001777-0aba28cd-7727-4bf4-ab1d-cf3a330daa7d.mp4

Can you reproduce the issue using this sample project I made from the project wizard in Intellij?

https://github.com/Unthrottled/flutter_demo

**Comment by pohuing** [comment]
The reactions are still incorrect. On windows these are ran through flutter.bat, which does return 0 on success as well. Can I hook into where the reactions are captured by the plugin?
![grafik](https://user-images.githubusercontent.com/24683548/191004196-dc318027-32a4-4956-9d08-38c922d44824.png)

**Comment by Unthrottled** [comment]
> Can I hook into where the reactions are captured by the plugin?

Perhaps, try this before we go this route.

Disable the `Build Tasks` and the `Observe Exit Codes` in the `Events` settings tab. Then try to reproduce the issue. I have a hunch that `Build Tasks` might be getting triggered.

**Comment by pohuing** [comment]
Looks like it
![grafik](https://user-images.githubusercontent.com/24683548/191005765-95b9cdbb-91cf-46b0-b4d6-832f54336a28.png)
![grafik](https://user-images.githubusercontent.com/24683548/191005793-59b330fe-0deb-43cf-8f82-18ce1e9df516.png)

**Comment by pohuing** [comment]
If I invert the settings, so enabled build tasks but not test results I don't see a reaction

**Comment by Unthrottled** [comment]
Okay, thanks. I'll have some time this weekend to look into trying to reproducing the `Exit Code` issue of the Debug Process on my Windows machine. I guess for the time being, you could just disable the Exit Code reaction

**Comment by Unthrottled** [comment]
I was able to reproduce & fix the issue. You can follow the [manual installation instructions](https://github.com/ani-memes/AMII#installation) after this [this github action completes](https://github.com/ani-memes/AMII/actions/runs/3143754065/jobs/5108872393). You can also re-enable the exit code & any other events you may have turned off as a work around.
