### ISSUE TITLE
[Bug]: Plugin 'Anime Memes' (version '1.1.8') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is IU-233.13135.103

### ISSUE THREAD

**Issue by AsunaMYAdmin** [ani-memes/AMII#177]
### Your Environment

* OS: Windows 10
* IntelliJ Product + version: IDEA Ultimate IU-233.13135.103
* Plugin version: 1.1.8

### How to reproduce.

Step One: Open Project

### What is expected?

To show up when the project started.

**Comment by syntafin** [comment]
Sadly seems to be dead as all the other plugins from @Unthrottled (for example the Doki Theme and Theme Icons)

**Comment by Unthrottled** [comment]
I haven’t bothered yet to publish the changes to the marketplace.

follow the manual installation instructions 

https://github.com/ani-memes/AMII#installation
