### ISSUE TITLE
[Bug]: Anime Memes not available in JetBrains Marketplace in WebStorm 2023.3.1

### ISSUE THREAD

**Issue by Vivallo04** [ani-memes/AMII#178]
### Your Environment

WebStorm 2023.3.1
Build #WS-233.11799.293, built on December 11, 2023
Licensed to Andrés Vivallo
Subscription is active until October 23, 2024.
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1970M
Cores: 12
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  io.unthrottled.amii (1.2.0) --> Installed manually (Please read "Some more notes" in the What is expected section)
  fr.gabrielcolson.prisma.prisma-intellij-plugin (1.2.5)
  com.jetbrains.darkPurpleTheme (1.3)
  com.vermouthx.idea (1.15.2)
  com.github.copilot (1.4.5.4049)
  com.alex.tokyonight (0.1.6)
  Intellij_GitHub_Dark_Theme (1.1.1)
  com.intellij.lang.jsgraphql (233.11799.172)
  com.nekofar.milad.intellij.nuxtjs (2.0.8)
  mobi.hsz.idea.gitignore (4.5.2)
  com.brandiico.jetbrains-nightfall-theme (2.0.0)

### How to reproduce.

Step One: Open Project
Step Two: Search for Anime Memes in Webstorm's Marketplace
**Anime Memes won't be found**

![image](https://github.com/ani-memes/AMII/assets/62166687/9f595192-0e27-4b72-8e94-4dc35037bec3)

### What is expected?

Anime Memes should be available in Webstorm's Marketplace

Some more notes: Before I decided to file this issue I had Anime Memes installed as a plugin using the Marketplace, it'd just not work because it wasn't compatible with Build #WS-233.11799.293 and it would not find any updated. I decided to remove it and do a manual installation which worked as expected. The last compatible build through the marketplace was 1.1.7 .

**Comment by CXwudi** [comment]
Same for IntelliJ, it's wired that it has been 3 weeks since [support for IntelliJ 2023.3](https://github.com/ani-memes/AMII/releases/tag/v1.2.0) is out, but JetBrain doesn't publish the newest update yet

**Comment by cwc329** [comment]
I think it is becauce the release action failed
https://github.com/ani-memes/AMII/actions/runs/7341641995
