### ISSUE TITLE
feat: 2024.1 plugin

### ISSUE THREAD

**Issue by MaikPeters1511** [ani-memes/AMII#179]
### Your Environment

wann kommt das plugin für die neue version?

### How to reproduce.

Step One: Open Project.

### What is expected?

To show up when the project started.

**Comment by CXwudi** [comment]
Would love to see the update to 2024.1

**Comment by MaikPeters1511** [comment]
> Would love to see the update to 2024.1

![image](https://github.com/ani-memes/AMII/assets/153079031/a8df27bf-5c0f-475e-af0d-e559195b4c0d)

**Comment by CXwudi** [comment]
Sorry I mean the update of this plugin to support 2024.1

**Comment by justjammin** [comment]
[https://github.com/ani-memes/AMII/releases/tag/v1.3.0](https://github.com/ani-memes/AMII/releases/tag/v1.3.0) Tested in PHPStorm 2024.1
