### ISSUE TITLE
清帮我翻译成汉语

### ISSUE THREAD

**Issue by Unthrottled** [ani-memes/AMII#50]
我想要翻译成汉字但是.....我是菜鸟 :sweat_smile: 
朋友们比我水平的普通话清帮我 :bow: 

(抱歉现在写中文很难）

**Comment by Yukio-Tanaka** [comment]
> 清帮我翻译成汉语

請幫我翻譯成中文

> 我想要翻译成汉字但是.....我是菜鸟 😅
> 朋友们比我水平的普通话清帮我 🙇

我想要翻譯成中文但是...我是新手😅
中文比我好的朋友們 請幫助我🙇

**Comment by gzzchh** [comment]
https://github.com/ani-memes/AMII/pull/111
在这里我更新了大部分翻译,有几句不知道应该如何翻译
