### ISSUE TITLE
Doesn't work 'Build' in Rider

### ISSUE THREAD

**Issue by the-shichko** [ani-memes/AMII#98]
Doesn't work 'Build' in Rider. Maybe I missed something, but there is a check mark on the field ''Build Tasks"

**Comment by Unthrottled** [comment]
I've asked about Rider in my initial investigation of #92 and apparently the Rider platform does things differently. I'll look into this as well when I try to to fix #92

**Comment by Unthrottled** [comment]
@the-shichko 
Good news! I figured it out. 

![Peek 2021-04-10 19-58](https://user-images.githubusercontent.com/15972415/114288890-d0fcb300-9a38-11eb-9c26-3f43dc147d64.gif)

It won't be part of this plugin, but an extension of this plugin that will enable this. I've got the extension created. I won't publish it to the public marketplace until a bit later. So you can wait until then, or you can follow the [manual installation instructions](https://github.com/ani-memes/amii-rider-extension#installation) and that should fix the issue for you.

I'll close this issue once the Rider extension is published and this plugin automatically suggests the Rider Extension.

**Comment by the-shichko** [comment]
Thanks)
